//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.18408
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

// 원래 파일 이름:
// 생성 날짜: 2017-03-16 오후 5:11:17
namespace Mod8WCFClient.FourthCoffeeDataService
{
    
    /// <summary>
    /// 스키마에 FourthCoffeeEntities에 대한 주석이 없습니다.
    /// </summary>
    public partial class FourthCoffeeEntities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// 새 FourthCoffeeEntities 개체를 초기화합니다.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public FourthCoffeeEntities(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// Visual Studio에서 이 서비스 참조에 대해 구성된 네임스페이스가
        /// 서버 스키마에 표시된 네임스페이스와 다르므로
        /// 두 네임스페이스 간을 매핑하려면 형식 매퍼를 사용합니다.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "FourthCoffeeModel", "Mod8WCFClient.FourthCoffeeDataService");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Visual Studio에서 이 서비스 참조에 대해 구성된 네임스페이스가
        /// 서버 스키마에 표시된 네임스페이스와 다르므로
        /// 두 네임스페이스 간을 매핑하려면 형식 매퍼를 사용합니다.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("Mod8WCFClient.FourthCoffeeDataService", global::System.StringComparison.Ordinal))
            {
                return string.Concat("FourthCoffeeModel.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// 스키마에 Branches에 대한 주석이 없습니다.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Branches> Branches
        {
            get
            {
                if ((this._Branches == null))
                {
                    this._Branches = base.CreateQuery<Branches>("Branches");
                }
                return this._Branches;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Branches> _Branches;
        /// <summary>
        /// 스키마에 Employees에 대한 주석이 없습니다.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Employees> Employees
        {
            get
            {
                if ((this._Employees == null))
                {
                    this._Employees = base.CreateQuery<Employees>("Employees");
                }
                return this._Employees;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Employees> _Employees;
        /// <summary>
        /// 스키마에 JobTitles에 대한 주석이 없습니다.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<JobTitles> JobTitles
        {
            get
            {
                if ((this._JobTitles == null))
                {
                    this._JobTitles = base.CreateQuery<JobTitles>("JobTitles");
                }
                return this._JobTitles;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<JobTitles> _JobTitles;
        /// <summary>
        /// 스키마에 Branches에 대한 주석이 없습니다.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToBranches(Branches branches)
        {
            base.AddObject("Branches", branches);
        }
        /// <summary>
        /// 스키마에 Employees에 대한 주석이 없습니다.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToEmployees(Employees employees)
        {
            base.AddObject("Employees", employees);
        }
        /// <summary>
        /// 스키마에 JobTitles에 대한 주석이 없습니다.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToJobTitles(JobTitles jobTitles)
        {
            base.AddObject("JobTitles", jobTitles);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"1.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"FourthCoffeeModel\" xmlns=\"http://schemas.microsoft.com/ado/2009/11/ed" +
                "m\"><EntityType Name=\"Branches\"><Key><PropertyRef Name=\"BranchID\" /></Key><Proper" +
                "ty Name=\"BranchID\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"BranchNam" +
                "e\" Type=\"Edm.String\" MaxLength=\"50\" FixedLength=\"false\" Unicode=\"false\" /><Navig" +
                "ationProperty Name=\"Employees\" Relationship=\"FourthCoffeeModel.FK_Employees_Bran" +
                "ches\" ToRole=\"Employees\" FromRole=\"Branches\" /></EntityType><EntityType Name=\"Em" +
                "ployees\"><Key><PropertyRef Name=\"EmployeeID\" /></Key><Property Name=\"EmployeeID\"" +
                " Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"FirstName\" Type=\"Edm.String" +
                "\" Nullable=\"false\" MaxLength=\"50\" FixedLength=\"false\" Unicode=\"false\" /><Propert" +
                "y Name=\"LastName\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"50\" FixedLength=" +
                "\"false\" Unicode=\"false\" /><Property Name=\"DateOfBirth\" Type=\"Edm.DateTime\" Preci" +
                "sion=\"0\" /><Property Name=\"Branch\" Type=\"Edm.Int32\" /><Property Name=\"JobTitle\" " +
                "Type=\"Edm.Int32\" /><NavigationProperty Name=\"Branches\" Relationship=\"FourthCoffe" +
                "eModel.FK_Employees_Branches\" ToRole=\"Branches\" FromRole=\"Employees\" /><Navigati" +
                "onProperty Name=\"JobTitles\" Relationship=\"FourthCoffeeModel.FK_Employees_JobTitl" +
                "es\" ToRole=\"JobTitles\" FromRole=\"Employees\" /></EntityType><EntityType Name=\"Job" +
                "Titles\"><Key><PropertyRef Name=\"JobTitleId\" /></Key><Property Name=\"JobTitleId\" " +
                "Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"Job\" Type=\"Edm.String\" MaxLe" +
                "ngth=\"50\" FixedLength=\"false\" Unicode=\"false\" /><NavigationProperty Name=\"Employ" +
                "ees\" Relationship=\"FourthCoffeeModel.FK_Employees_JobTitles\" ToRole=\"Employees\" " +
                "FromRole=\"JobTitles\" /></EntityType><Association Name=\"FK_Employees_Branches\"><E" +
                "nd Type=\"FourthCoffeeModel.Branches\" Role=\"Branches\" Multiplicity=\"0..1\" /><End " +
                "Type=\"FourthCoffeeModel.Employees\" Role=\"Employees\" Multiplicity=\"*\" /><Referent" +
                "ialConstraint><Principal Role=\"Branches\"><PropertyRef Name=\"BranchID\" /></Princi" +
                "pal><Dependent Role=\"Employees\"><PropertyRef Name=\"Branch\" /></Dependent></Refer" +
                "entialConstraint></Association><Association Name=\"FK_Employees_JobTitles\"><End T" +
                "ype=\"FourthCoffeeModel.JobTitles\" Role=\"JobTitles\" Multiplicity=\"0..1\" /><End Ty" +
                "pe=\"FourthCoffeeModel.Employees\" Role=\"Employees\" Multiplicity=\"*\" /><Referentia" +
                "lConstraint><Principal Role=\"JobTitles\"><PropertyRef Name=\"JobTitleId\" /></Princ" +
                "ipal><Dependent Role=\"Employees\"><PropertyRef Name=\"JobTitle\" /></Dependent></Re" +
                "ferentialConstraint></Association></Schema><Schema Namespace=\"Mod8WCFDataService" +
                "\" xmlns=\"http://schemas.microsoft.com/ado/2009/11/edm\"><EntityContainer Name=\"Fo" +
                "urthCoffeeEntities\" m:IsDefaultEntityContainer=\"true\" p6:LazyLoadingEnabled=\"tru" +
                "e\" xmlns:p6=\"http://schemas.microsoft.com/ado/2009/02/edm/annotation\"><EntitySet" +
                " Name=\"Branches\" EntityType=\"FourthCoffeeModel.Branches\" /><EntitySet Name=\"Empl" +
                "oyees\" EntityType=\"FourthCoffeeModel.Employees\" /><EntitySet Name=\"JobTitles\" En" +
                "tityType=\"FourthCoffeeModel.JobTitles\" /><FunctionImport Name=\"AllEmployees\" Ret" +
                "urnType=\"Collection(FourthCoffeeModel.Employees)\" EntitySet=\"Employees\" m:HttpMe" +
                "thod=\"GET\" /><FunctionImport Name=\"EmployeesByID\" ReturnType=\"Collection(FourthC" +
                "offeeModel.Employees)\" EntitySet=\"Employees\" m:HttpMethod=\"GET\"><Parameter Name=" +
                "\"id\" Type=\"Edm.Int32\" Nullable=\"false\" /></FunctionImport><AssociationSet Name=\"" +
                "FK_Employees_Branches\" Association=\"FourthCoffeeModel.FK_Employees_Branches\"><En" +
                "d Role=\"Branches\" EntitySet=\"Branches\" /><End Role=\"Employees\" EntitySet=\"Employ" +
                "ees\" /></AssociationSet><AssociationSet Name=\"FK_Employees_JobTitles\" Associatio" +
                "n=\"FourthCoffeeModel.FK_Employees_JobTitles\"><End Role=\"Employees\" EntitySet=\"Em" +
                "ployees\" /><End Role=\"JobTitles\" EntitySet=\"JobTitles\" /></AssociationSet></Enti" +
                "tyContainer></Schema></edmx:DataServices></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// 스키마에 FourthCoffeeModel.Branches에 대한 주석이 없습니다.
    /// </summary>
    /// <KeyProperties>
    /// BranchID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Branches")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("BranchID")]
    public partial class Branches : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// 새 Branches 개체를 만듭니다.
        /// </summary>
        /// <param name="branchID">BranchID의 초기 값입니다.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Branches CreateBranches(int branchID)
        {
            Branches branches = new Branches();
            branches.BranchID = branchID;
            return branches;
        }
        /// <summary>
        /// 스키마에 Property BranchID에 대한 주석이 없습니다.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int BranchID
        {
            get
            {
                return this._BranchID;
            }
            set
            {
                this.OnBranchIDChanging(value);
                this._BranchID = value;
                this.OnBranchIDChanged();
                this.OnPropertyChanged("BranchID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _BranchID;
        partial void OnBranchIDChanging(int value);
        partial void OnBranchIDChanged();
        /// <summary>
        /// 스키마에 Property BranchName에 대한 주석이 없습니다.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string BranchName
        {
            get
            {
                return this._BranchName;
            }
            set
            {
                this.OnBranchNameChanging(value);
                this._BranchName = value;
                this.OnBranchNameChanged();
                this.OnPropertyChanged("BranchName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _BranchName;
        partial void OnBranchNameChanging(string value);
        partial void OnBranchNameChanged();
        /// <summary>
        /// 스키마에 Employees에 대한 주석이 없습니다.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Employees> Employees
        {
            get
            {
                return this._Employees;
            }
            set
            {
                this._Employees = value;
                this.OnPropertyChanged("Employees");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Employees> _Employees = new global::System.Data.Services.Client.DataServiceCollection<Employees>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// 스키마에 FourthCoffeeModel.Employees에 대한 주석이 없습니다.
    /// </summary>
    /// <KeyProperties>
    /// EmployeeID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Employees")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("EmployeeID")]
    public partial class Employees : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// 새 Employees 개체를 만듭니다.
        /// </summary>
        /// <param name="employeeID">EmployeeID의 초기 값입니다.</param>
        /// <param name="firstName">FirstName의 초기 값입니다.</param>
        /// <param name="lastName">LastName의 초기 값입니다.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Employees CreateEmployees(int employeeID, string firstName, string lastName)
        {
            Employees employees = new Employees();
            employees.EmployeeID = employeeID;
            employees.FirstName = firstName;
            employees.LastName = lastName;
            return employees;
        }
        /// <summary>
        /// 스키마에 Property EmployeeID에 대한 주석이 없습니다.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int EmployeeID
        {
            get
            {
                return this._EmployeeID;
            }
            set
            {
                this.OnEmployeeIDChanging(value);
                this._EmployeeID = value;
                this.OnEmployeeIDChanged();
                this.OnPropertyChanged("EmployeeID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _EmployeeID;
        partial void OnEmployeeIDChanging(int value);
        partial void OnEmployeeIDChanged();
        /// <summary>
        /// 스키마에 Property FirstName에 대한 주석이 없습니다.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string FirstName
        {
            get
            {
                return this._FirstName;
            }
            set
            {
                this.OnFirstNameChanging(value);
                this._FirstName = value;
                this.OnFirstNameChanged();
                this.OnPropertyChanged("FirstName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _FirstName;
        partial void OnFirstNameChanging(string value);
        partial void OnFirstNameChanged();
        /// <summary>
        /// 스키마에 Property LastName에 대한 주석이 없습니다.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string LastName
        {
            get
            {
                return this._LastName;
            }
            set
            {
                this.OnLastNameChanging(value);
                this._LastName = value;
                this.OnLastNameChanged();
                this.OnPropertyChanged("LastName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _LastName;
        partial void OnLastNameChanging(string value);
        partial void OnLastNameChanged();
        /// <summary>
        /// 스키마에 Property DateOfBirth에 대한 주석이 없습니다.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> DateOfBirth
        {
            get
            {
                return this._DateOfBirth;
            }
            set
            {
                this.OnDateOfBirthChanging(value);
                this._DateOfBirth = value;
                this.OnDateOfBirthChanged();
                this.OnPropertyChanged("DateOfBirth");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _DateOfBirth;
        partial void OnDateOfBirthChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnDateOfBirthChanged();
        /// <summary>
        /// 스키마에 Property Branch에 대한 주석이 없습니다.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> Branch
        {
            get
            {
                return this._Branch;
            }
            set
            {
                this.OnBranchChanging(value);
                this._Branch = value;
                this.OnBranchChanged();
                this.OnPropertyChanged("Branch");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _Branch;
        partial void OnBranchChanging(global::System.Nullable<int> value);
        partial void OnBranchChanged();
        /// <summary>
        /// 스키마에 Property JobTitle에 대한 주석이 없습니다.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> JobTitle
        {
            get
            {
                return this._JobTitle;
            }
            set
            {
                this.OnJobTitleChanging(value);
                this._JobTitle = value;
                this.OnJobTitleChanged();
                this.OnPropertyChanged("JobTitle");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _JobTitle;
        partial void OnJobTitleChanging(global::System.Nullable<int> value);
        partial void OnJobTitleChanged();
        /// <summary>
        /// 스키마에 Branches에 대한 주석이 없습니다.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Branches Branches
        {
            get
            {
                return this._Branches;
            }
            set
            {
                this._Branches = value;
                this.OnPropertyChanged("Branches");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Branches _Branches;
        /// <summary>
        /// 스키마에 JobTitles에 대한 주석이 없습니다.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public JobTitles JobTitles
        {
            get
            {
                return this._JobTitles;
            }
            set
            {
                this._JobTitles = value;
                this.OnPropertyChanged("JobTitles");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private JobTitles _JobTitles;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// 스키마에 FourthCoffeeModel.JobTitles에 대한 주석이 없습니다.
    /// </summary>
    /// <KeyProperties>
    /// JobTitleId
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("JobTitles")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("JobTitleId")]
    public partial class JobTitles : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// 새 JobTitles 개체를 만듭니다.
        /// </summary>
        /// <param name="jobTitleId">JobTitleId의 초기 값입니다.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static JobTitles CreateJobTitles(int jobTitleId)
        {
            JobTitles jobTitles = new JobTitles();
            jobTitles.JobTitleId = jobTitleId;
            return jobTitles;
        }
        /// <summary>
        /// 스키마에 Property JobTitleId에 대한 주석이 없습니다.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int JobTitleId
        {
            get
            {
                return this._JobTitleId;
            }
            set
            {
                this.OnJobTitleIdChanging(value);
                this._JobTitleId = value;
                this.OnJobTitleIdChanged();
                this.OnPropertyChanged("JobTitleId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _JobTitleId;
        partial void OnJobTitleIdChanging(int value);
        partial void OnJobTitleIdChanged();
        /// <summary>
        /// 스키마에 Property Job에 대한 주석이 없습니다.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Job
        {
            get
            {
                return this._Job;
            }
            set
            {
                this.OnJobChanging(value);
                this._Job = value;
                this.OnJobChanged();
                this.OnPropertyChanged("Job");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Job;
        partial void OnJobChanging(string value);
        partial void OnJobChanged();
        /// <summary>
        /// 스키마에 Employees에 대한 주석이 없습니다.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Employees> Employees
        {
            get
            {
                return this._Employees;
            }
            set
            {
                this._Employees = value;
                this.OnPropertyChanged("Employees");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Employees> _Employees = new global::System.Data.Services.Client.DataServiceCollection<Employees>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
